#pragma once

#define DISABLE_RGB_MATRIX_PIXEL_FLOW
#define DISABLE_RGB_MATRIX_PIXEL_FRACTAL
#define DISABLE_RGB_MATRIX_PIXEL_RAIN

#define VIAL_KEYBOARD_UID {0x74, 0xBB, 0xD7, 0xDF, 0xAE, 0xC1, 0x97, 0xB3}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 2
